backend:
  image:
    repository: ghcr.io/get-convex/convex-backend
    tag: 6efab6f2b6c182b90255774d747328cfc7b80dd9
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 3210
    siteProxyPort: 3211
  
  env:
    instanceName: "convex-instance"
    instanceSecret: "your-secret-here"
    releaseVersion: "dev"
    databaseUrl: "sqlite:///data/convex.db"
    rustLog: "info"
  
  persistence:
    enabled: true
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 10Gi

dashboard:
  image:
    repository: ghcr.io/get-convex/convex-dashboard
    tag: 6efab6f2b6c182b90255774d747328cfc7b80dd9
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 6791

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: convex.local
      paths:
        - path: /
          pathType: Prefix
          service: backend
        - path: /dashboard
          pathType: Prefix
          service: dashboard
  tls: []

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}