apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "convex.fullname" . }}-backend
  labels:
    {{- include "convex.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "convex.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "convex.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      {{- with .Values.serviceAccount }}
      serviceAccountName: {{ include "convex.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: backend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3210
              protocol: TCP
            - name: site-proxy
              containerPort: 3211
              protocol: TCP
          env:
            - name: INSTANCE_NAME
              value: {{ .Values.backend.env.instanceName | quote }}
            - name: INSTANCE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "convex.fullname" . }}-secret
                  key: instance-secret
            - name: CONVEX_RELEASE_VERSION_DEV
              value: {{ .Values.backend.env.releaseVersion | quote }}
            - name: DATABASE_URL
              value: {{ .Values.backend.env.databaseUrl | quote }}
            - name: RUST_LOG
              value: {{ .Values.backend.env.rustLog | quote }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.backend.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: /data
          {{- end }}
      {{- if .Values.backend.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "convex.fullname" . }}-data
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}