apiVersion: apps/v1
kind: Deployment
metadata:
  name: convex-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: convex-backend
  template:
    metadata:
      labels:
        app: convex-backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.image.backend }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 3210
        - containerPort: 3211
        envFrom:
        - configMapRef:
            name: convex-config
        - secretRef:
            name: {{ .Values.existingSecret }}
        livenessProbe:
          httpGet:
            path: /
            port: 3210
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3210
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: convex-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: convex-dashboard
  template:
    metadata:
      labels:
        app: convex-dashboard
    spec:
      containers:
      - name: dashboard
        image: {{ .Values.image.dashboard }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 6791
        livenessProbe:
          httpGet:
            path: /
            port: 6791
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 6791
          initialDelaySeconds: 5
          periodSeconds: 5