apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: convex-ingress
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: convex-backend
            port:
              number: 3210
      - path: /dashboard
        pathType: Prefix
        backend:
          service:
            name: convex-dashboard
            port:
              number: 6791