apiVersion: v1
kind: Secret
metadata:
  name: {{ include "convex.fullname" . }}-secret
  labels:
    {{- include "convex.labels" . | nindent 4 }}
type: Opaque
data:
  instance-secret: {{ .Values.backend.env.instanceSecret | b64enc }}