apiVersion: v1
kind: Service
metadata:
  name: convex-backend
spec:
  selector:
    app: convex-backend
  ports:
  - name: http
    port: 3210
    targetPort: 3210
  - name: site-proxy
    port: 3211
    targetPort: 3211
---
apiVersion: v1
kind: Service
metadata:
  name: convex-dashboard
spec:
  selector:
    app: convex-dashboard
  ports:
  - name: http
    port: 6791
    targetPort: 6791